#!/usr/bin/env node
// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Jupiter Industries (Liam Crowter) and the 2d6mcp maintainers

import { writeFileSync, existsSync, mkdirSync, unlinkSync } from "node:fs";
import { resolve } from "node:path";
import { PROJECT_ROOT, BYOD_CONSENT_FILE } from "./config.js";
import { populateOglDatabase } from "@2d6mcp/ogl/populate";
import { populateDwDatabase } from "@2d6mcp/dw/populate";
import { populateBrpDatabase } from "@2d6mcp/brp/populate";
import { populate5ecompatibleDatabase } from "@2d6mcp/5ecompatible/populate";
import { populateOrcusDatabase } from "@2d6mcp/orcus/populate";

function cmdSetup(): void {
  if (existsSync(BYOD_CONSENT_FILE)) {
    console.log("BYOD consent token already exists at:", BYOD_CONSENT_FILE);
    console.log("BYOD Mode is enabled.");
    return;
  }

  writeFileSync(
    BYOD_CONSENT_FILE,
    `# BYOD Consent Token
# Generated by 2d6mcp setup command
# By keeping this file, you confirm the following:
#
# "By enabling local file ingestion (BYOD Mode), I confirm that I am the legal
# owner of the imported files or hold a valid license to use them. The developers
# of this software do not condone piracy or the unauthorized distribution of
# copyrighted tabletop roleplaying materials."
#
# Created: ${new Date().toISOString()}
`
  );

  mkdirSync(resolve(PROJECT_ROOT, "data", "byod"), { recursive: true });

  console.log("BYOD consent token created at:", BYOD_CONSENT_FILE);
  console.log("BYOD Mode is now enabled.");
  console.log("Set BYOD_PATH in your environment to point to your local RPG source files.");
}

function cmdPopulate(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "ogl", "cepheus.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("Database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    unlinkSync(dbPath);
  }

  const result = populateOglDatabase(dbPath);
  console.log(result.message);
}

function cmdHelp(): void {
  console.log(`2D6 MCP Server CLI

Usage:
  2d6mcp setup         Create the BYOD consent token
  2d6mcp populate-ogl  Generate or regenerate the OGL SQLite database
  2d6mcp populate-ogl --force  Force regeneration of OGL database
   2d6mcp populate-dw   Generate or regenerate the Dungeon World SQLite database
   2d6mcp populate-dw --force   Force regeneration of DW database
    2d6mcp populate-brp  Generate or regenerate the Basic Roleplaying SQLite database
    2d6mcp populate-brp --force  Force regeneration of BRP database
  2d6mcp populate-5ecompatible  Generate or regenerate the 5E-compatible SRD database
  2d6mcp populate-5ecompatible --force  Force regeneration of 5E database
  2d6mcp populate-orcus  Generate or regenerate the Orcus d20-compatible database
  2d6mcp populate-orcus --force  Force regeneration of Orcus database
  2d6mcp help          Show this help

 Environment:
   AGREE_BYOD_USE=true   Enable BYOD via env var
    BYOD_PATH=/path/to/files       Directory of local RPG source files
    OGL_DB_PATH=/path/to/db        Custom OGL database path (optional)
    DW_DB_PATH=/path/to/db         Custom DW database path (optional)
    BRP_DB_PATH=/path/to/db        Custom BRP database path (optional)
    SR5E_DB_PATH=/path/to/db       Custom 5E-compatible database path (optional)
  ORCUS_DB_PATH=/path/to/db       Custom Orcus database path (optional)
`);
}

function cmdPopulateDw(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "dw", "dungeon-world.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("DW database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    unlinkSync(dbPath);
  }

  const result = populateDwDatabase(dbPath);
  console.log(result.message);
}

function cmdPopulateBrp(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "brp", "basic-roleplaying.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("BRP database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    unlinkSync(dbPath);
  }

  const result = populateBrpDatabase(dbPath);
  console.log(result.message);
}

function cmdPopulate5ecompatible(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "5ecompatible", "5ecompatible-srd.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("5E-compatible database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    unlinkSync(dbPath);
  }

  const result = populate5ecompatibleDatabase(dbPath);
  console.log(result.message);
}

function cmdPopulateOrcus(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "orcus", "orcus.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("Orcus database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    unlinkSync(dbPath);
  }

  const result = populateOrcusDatabase(dbPath);
  console.log(result.message);
}

const command = process.argv[2]?.toLowerCase() || "help";

switch (command) {
  case "setup":
    cmdSetup();
    break;
  case "populate-ogl":
    cmdPopulate();
    break;
  case "populate-dw":
    cmdPopulateDw();
    break;
  case "populate-brp":
    cmdPopulateBrp();
    break;
  case "populate-5ecompatible":
    cmdPopulate5ecompatible();
    break;
  case "populate-orcus":
    cmdPopulateOrcus();
    break;
  case "help":
  case "--help":
  case "-h":
    cmdHelp();
    break;
  default:
    console.error(`Unknown command: ${command}`);
    cmdHelp();
    process.exit(1);
}
