#!/usr/bin/env node

import { writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { PROJECT_ROOT, BYOD_CONSENT_FILE } from "./config.js";
import { populateOglDatabase } from "./ogl/populate.js";

function cmdSetup(): void {
  if (existsSync(BYOD_CONSENT_FILE)) {
    console.log("BYOD consent token already exists at:", BYOD_CONSENT_FILE);
    console.log("BYOD Mode is enabled.");
    return;
  }

  writeFileSync(
    BYOD_CONSENT_FILE,
    `# BYOD Consent Token
# Generated by 2d6mcp setup command
# By keeping this file, you confirm the following:
#
# "By enabling local file ingestion (BYOD Mode), I confirm that I am the legal
# owner of the imported files or hold a valid license to use them. The developers
# of this software do not condone piracy or the unauthorized distribution of
# copyrighted tabletop roleplaying materials."
#
# Created: ${new Date().toISOString()}
`
  );

  mkdirSync(resolve(PROJECT_ROOT, "data", "byod"), { recursive: true });

  console.log("BYOD consent token created at:", BYOD_CONSENT_FILE);
  console.log("BYOD Mode is now enabled.");
  console.log("Set BYOD_PATH in your environment to point to your local RPG source files.");
}

function cmdPopulate(): void {
  const dbPath = resolve(PROJECT_ROOT, "data", "ogl", "cepheus.db");
  const force = process.argv.includes("--force");

  if (existsSync(dbPath) && !force) {
    console.log("Database already exists. Use --force to overwrite.");
    return;
  }

  if (force && existsSync(dbPath)) {
    const { unlinkSync } = require("node:fs");
    unlinkSync(dbPath);
  }

  const result = populateOglDatabase(dbPath);
  console.log(result.message);
}

function cmdHelp(): void {
  console.log(`2D6 MCP Server CLI

Usage:
  2d6mcp setup         Create the BYOD consent token
  2d6mcp populate-ogl  Generate or regenerate the OGL SQLite database
  2d6mcp populate-ogl --force  Force regeneration of OGL database
  2d6mcp help          Show this help

Environment:
  AGREE_BYOD_USE=true   Enable BYOD via env var
  BYOD_PATH=/path/to/files       Directory of local RPG source files
  OGL_DB_PATH=/path/to/db        Custom OGL database path (optional)
`);
}

const command = process.argv[2]?.toLowerCase() || "help";

switch (command) {
  case "setup":
    cmdSetup();
    break;
  case "populate-ogl":
    cmdPopulate();
    break;
  case "help":
  case "--help":
  case "-h":
    cmdHelp();
    break;
  default:
    console.error(`Unknown command: ${command}`);
    cmdHelp();
    process.exit(1);
}
